### PR TITLE
Return HTTP 400 Bad Request for unknown instance in last operation

### LINKED ISSUE #306: polling last operation with throwing ServiceInstanceDoesNotExistException returns 422 instead of 404
I have implemented the `ServiceInstanceService` interface. My `getLastOperation` pseudocode looks like this (of course wrapped in mono):
```
return getDeployment(serviceId, planId, instanceId)
        .map(deployment ->
                taskClient.getTask(deployment.operationId())
        )
        .map(taskMapper::mapTaskToLastServiceOperationResponse)
        .orElseThrow(() -> new ServiceInstanceDoesNotExistException(instanceId));
```

If the instance, of wich last operation is questioned, does not exists (failed to create when provisioning), I throw an ServiceInstanceDoesNotExistException according to guidance in comments inside interface for this method. Unfortunately, the spring osb returns in such case 422 http status and the platform does not cease polling `getLastOperation`. By the OSB API specification, 404 or 410 should be returned. I was unsuccesfull to find the reason for that status, but I think somewhere below these lines:
https://github.com/spring-cloud/spring-cloud-open-service-broker/blob/fd1a6db9717d35bf4df851db998866064d86ab22/spring-cloud-open-service-broker-core/src/main/java/org/springframework/cloud/servicebroker/controller/ServiceInstanceController.java#L243-L247

should be similar code that is in deleteDeployment method
https://github.com/spring-cloud/spring-cloud-open-service-broker/blob/fd1a6db9717d35bf4df851db998866064d86ab22/spring-cloud-open-service-broker-core/src/main/java/org/springframework/cloud/servicebroker/controller/ServiceInstanceController.java#L300-L307

Or did I understand it wrongly?

### PR DESCRIPTION
**Pull request by royclarkson**
v2.15 of the OSB API spec is a little unclear about how to handle the
scenario where a request is made for the last operation of an instance id
that does not exist and never existed. It does specify a 400 Bad Request
for "malformed or missing mandatory data". In this case an unknown instance
id is provided, so it's the best option for response code.

The spec is improved in v2.16. There, it adds a 404 Not Found for this
scenario. We'll change this when we move to the newer spec.

Resolves #306

### CODE REVIEW

File: spring-cloud-open-service-broker-core/src/main/java/org/springframework/cloud/servicebroker/controller/ServiceInstanceController.java [hunk 1]
```diff
@@ -241,9 +241,18 @@ else if (response.isInstanceExisted()) {
...
 				.map(response -> {
-					boolean isSuccessfulDelete = response.getState().equals(OperationState.SUCCEEDED) && response
+					boolean isSuccessfulDelete = OperationState.SUCCEEDED.equals(response.getState()) && response
 							.isDeleteOperation();
 					return new ResponseEntity<>(response, isSuccessfulDelete ? HttpStatus.GONE : HttpStatus.OK);
+				})
+				.onErrorResume(e -> {
+					if (e instanceof ServiceInstanceDoesNotExistException) {
+						// TODO: v2.16 of the OSB API spec changes this to an HTTP 404
+						return Mono.just(new ResponseEntity<>(HttpStatus.BAD_REQUEST));
```
Comment (LittleBaiBai) [inline spring-cloud-open-service-broker-core/src/main/java/org/springframework/cloud/servicebroker/controller/ServiceInstanceController.java:251]: I haven't checked the OSB spec yet, but it would be nice if we can add response body to explain the error here.

**Review by LittleBaiBai — APPROVED** [review]

File: spring-cloud-open-service-broker-core/src/main/java/org/springframework/cloud/servicebroker/controller/ServiceInstanceController.java (hunk 1 above)
Comment (royclarkson) [reply spring-cloud-open-service-broker-core/src/main/java/org/springframework/cloud/servicebroker/controller/ServiceInstanceController.java:251]: That's a good idea. There's a `description` field that I can use for that. Thanks!

Comment (royclarkson) [reply spring-cloud-open-service-broker-core/src/main/java/org/springframework/cloud/servicebroker/controller/ServiceInstanceController.java]: done. updated to include a description.

**Comment by juan-palacios** [comment]
Can we also update the JavaDoc for `ServiceInstanceDoesNotExistException`? Currently there's no indication of this. I was bumping libraries in my repository and trying to understand why the `ServiceBrokerExceptionHandler` was not kicking in until I debugged to these changes.
